"""
============================================================
Python for Engineering and Research
08 - Plot Data from CSV
============================================================

Purpose:
    Demonstrate how engineering and research data stored in
    CSV files can be loaded, inspected, selected, processed,
    visualized, and exported using Pandas and Matplotlib.

Topics:
    1. What is a CSV file?
    2. Required libraries
    3. File paths
    4. Reading CSV using Pandas
    5. Inspecting the dataset
    6. Column names
    7. Data types
    8. Selecting columns
    9. Plotting one variable
    10. Plotting selected variables
    11. Different physical units
    12. Subplots from CSV
    13. Filtering data
    14. Handling missing values
    15. Handling invalid column names
    16. Reusable plotting function
    17. Saving figures
    18. Common mistakes
    19. Key takeaways

Sample File:
    sample_data/voltage_current.csv

Expected Columns:
    Time_s
    Voltage_V
    Current_A
    Power_W

Author:
    Arsalan Muhammad Soomar
============================================================
"""


# ============================================================
# 1. WHAT IS A CSV FILE?
# ============================================================

"""
CSV means:

Comma-Separated Values


A CSV file stores tabular data.

Example:

Time_s,Voltage_V,Current_A,Power_W
0.0000,48.000,2.200,105.600
0.0010,48.618,2.407,117.020
0.0020,49.176,2.637,129.680


CSV files are commonly generated by:

- Oscilloscopes
- Simulation software
- Measurement equipment
- Data acquisition systems
- MATLAB
- LabVIEW
- Python
- Engineering software
- Experimental test systems
"""


# ============================================================
# 2. REQUIRED LIBRARIES
# ============================================================

"""
Pandas:

Used to read and manipulate tabular data.

Matplotlib:

Used to visualize the data.

Pathlib:

Used to create reliable file paths.
"""


import pandas as pd
import matplotlib.pyplot as plt

from pathlib import Path


# ============================================================
# 3. PACKAGE INSTALLATION
# ============================================================

"""
If Pandas or Matplotlib is not installed, run:

pip install pandas matplotlib


This command should normally be executed in the terminal,
not inside this Python script.
"""


# ============================================================
# 4. LOCATE THE CSV FILE
# ============================================================

"""
Repository structure:

02_Data_Visualization/
│
├── 08_plot_from_csv.py
│
└── sample_data/
    └── voltage_current.csv


Using pathlib allows the script to locate sample_data
relative to the Python file itself.
"""


script_folder = Path(
    __file__
).resolve().parent


csv_file = (
    script_folder
    / "sample_data"
    / "voltage_current.csv"
)


print(
    "--- CSV File Path ---"
)

print(
    csv_file
)


# ============================================================
# 5. CHECK WHETHER FILE EXISTS
# ============================================================

"""
Before attempting to read the file, check whether it exists.

This produces a clearer error message than allowing the
script to fail later.
"""


if not csv_file.exists():

    raise FileNotFoundError(
        f"\nCSV file not found:\n{csv_file}\n"
        "\nCheck that the sample_data folder exists "
        "and contains voltage_current.csv."
    )


print(
    "\nCSV file found successfully."
)


# ============================================================
# 6. READ CSV USING PANDAS
# ============================================================

"""
Pandas reads CSV files using:

pd.read_csv()
"""


data = pd.read_csv(
    csv_file
)


print(
    "\nCSV loaded successfully."
)


# ============================================================
# 7. DISPLAY THE DATASET
# ============================================================

"""
Printing the DataFrame displays the complete table
for small datasets.
"""


print(
    "\n--- Complete Dataset ---"
)

print(
    data
)


# ============================================================
# 8. DISPLAY FIRST ROWS
# ============================================================

"""
head() displays the first five rows by default.

This is one of the first commands researchers should use
after loading an unfamiliar dataset.
"""


print(
    "\n--- First Five Rows ---"
)

print(
    data.head()
)


# Display first 3 rows

print(
    "\n--- First Three Rows ---"
)

print(
    data.head(
        3
    )
)


# ============================================================
# 9. DISPLAY LAST ROWS
# ============================================================

"""
tail() displays the final rows.
"""


print(
    "\n--- Last Five Rows ---"
)

print(
    data.tail()
)


# ============================================================
# 10. CHECK DATASET SHAPE
# ============================================================

"""
shape returns:

(number_of_rows, number_of_columns)
"""


print(
    "\n--- Dataset Shape ---"
)

print(
    data.shape
)


print(
    "Number of Rows:",
    data.shape[0]
)

print(
    "Number of Columns:",
    data.shape[1]
)


# ============================================================
# 11. CHECK COLUMN NAMES
# ============================================================

"""
This is EXTREMELY important when working with CSV files.

Never assume the column names.

Always inspect:

data.columns
"""


print(
    "\n--- Column Names ---"
)

print(
    data.columns
)


# Convert to ordinary Python list

column_names = data.columns.tolist()


print(
    "\nColumn List:"
)

print(
    column_names
)


# ============================================================
# 12. CHECK DATA TYPES
# ============================================================

"""
dtypes shows the data type of every column.

Common Pandas types:

float64
int64
object
bool


For engineering calculations, numerical columns should
normally be numeric rather than text/object.
"""


print(
    "\n--- Data Types ---"
)

print(
    data.dtypes
)


# ============================================================
# 13. DATASET INFORMATION
# ============================================================

"""
info() provides:

- Column names
- Number of non-null entries
- Data types
- Memory information
"""


print(
    "\n--- Dataset Information ---"
)

data.info()


# ============================================================
# 14. BASIC STATISTICS
# ============================================================

"""
describe() calculates useful statistics for numerical
columns.

Examples:

count
mean
standard deviation
minimum
maximum
quartiles
"""


print(
    "\n--- Basic Statistics ---"
)

print(
    data.describe()
)


# ============================================================
# 15. SELECT ONE COLUMN
# ============================================================

"""
A Pandas column can be selected using:

data["Column_Name"]
"""


time = data[
    "Time_s"
]


voltage = data[
    "Voltage_V"
]


print(
    "\n--- Time Column ---"
)

print(
    time
)


print(
    "\n--- Voltage Column ---"
)

print(
    voltage
)


# ============================================================
# 16. BASIC CSV LINE PLOT
# ============================================================

"""
Now plot:

Voltage vs Time
"""


fig, ax = plt.subplots(
    figsize=(7, 4.5)
)


ax.plot(
    time,
    voltage,
    linewidth=2
)


ax.set_xlabel(
    "Time [s]"
)

ax.set_ylabel(
    "Voltage [V]"
)

ax.set_title(
    "Voltage vs Time from CSV"
)


ax.grid(
    True
)


plt.tight_layout()

plt.show()


# ============================================================
# 17. SELECT CURRENT
# ============================================================

current = data[
    "Current_A"
]


fig, ax = plt.subplots(
    figsize=(7, 4.5)
)


ax.plot(
    time,
    current,
    linewidth=2
)


ax.set_xlabel(
    "Time [s]"
)

ax.set_ylabel(
    "Current [A]"
)

ax.set_title(
    "Current vs Time from CSV"
)


ax.grid(
    True
)


plt.tight_layout()

plt.show()


# ============================================================
# 18. SELECT POWER
# ============================================================

power = data[
    "Power_W"
]


fig, ax = plt.subplots(
    figsize=(7, 4.5)
)


ax.plot(
    time,
    power,
    linewidth=2
)


ax.set_xlabel(
    "Time [s]"
)

ax.set_ylabel(
    "Power [W]"
)

ax.set_title(
    "Power vs Time from CSV"
)


ax.grid(
    True
)


plt.tight_layout()

plt.show()


# ============================================================
# 19. SELECT X AND Y BY VARIABLE NAME
# ============================================================

"""
This structure makes the script easier to modify.

To change the figure, only change:

x_column

y_column
"""


x_column = "Time_s"

y_column = "Voltage_V"


x_data = data[
    x_column
]


y_data = data[
    y_column
]


fig, ax = plt.subplots(
    figsize=(7, 4.5)
)


ax.plot(
    x_data,
    y_data,
    linewidth=2
)


ax.set_xlabel(
    "Time [s]"
)

ax.set_ylabel(
    "Voltage [V]"
)

ax.set_title(
    "Selected CSV Columns"
)


ax.grid(
    True
)


plt.tight_layout()

plt.show()


# ============================================================
# 20. CHECK WHETHER SELECTED COLUMN EXISTS
# ============================================================

"""
A common error is typing the wrong column name.

For example:

"Voltage"

when the actual CSV column is:

"Voltage_V"
"""


selected_column = "Voltage_V"


if selected_column in data.columns:

    print(
        f"\nColumn found: "
        f"{selected_column}"
    )

else:

    print(
        f"\nColumn not found: "
        f"{selected_column}"
    )


# ============================================================
# 21. SAFE COLUMN-SELECTION FUNCTION
# ============================================================

def check_column(
    dataframe,
    column_name
):
    """
    Check whether a column exists in a Pandas DataFrame.

    Parameters
    ----------
    dataframe : pandas.DataFrame
        Input dataset.

    column_name : str
        Column to check.

    Raises
    ------
    KeyError
        If the requested column does not exist.
    """

    if column_name not in dataframe.columns:

        raise KeyError(
            f"\nColumn '{column_name}' not found."
            f"\nAvailable columns:"
            f"\n{dataframe.columns.tolist()}"
        )


# Example

check_column(
    data,
    "Voltage_V"
)


# ============================================================
# 22. PLOT TWO VARIABLES FROM CSV
# ============================================================

"""
Suppose we want:

Voltage

and

Current

versus Time.


Technically, Matplotlib allows them to share one axis.
"""


fig, ax = plt.subplots(
    figsize=(7, 4.5)
)


ax.plot(
    data["Time_s"],
    data["Voltage_V"],
    label="Voltage"
)


ax.plot(
    data["Time_s"],
    data["Current_A"],
    label="Current"
)


ax.set_xlabel(
    "Time [s]"
)

ax.set_ylabel(
    "Mixed Units"
)

ax.set_title(
    "Voltage and Current on One Axis"
)


ax.grid(
    True
)

ax.legend()


plt.tight_layout()

plt.show()


# ============================================================
# 23. IMPORTANT: DIFFERENT PHYSICAL UNITS
# ============================================================

"""
The previous plot is valid Python.

However:

Voltage [V]

and

Current [A]

have different physical units.


Therefore using one common Y-axis labeled:

"Mixed Units"

is usually NOT ideal for a scientific figure.

Better choices include:

- Separate plots
- Subplots
- Dual Y-axis
- Normalization


Here we use subplots.
"""


# ============================================================
# 24. PLOT MULTIPLE CSV VARIABLES USING SUBPLOTS
# ============================================================

fig, axes = plt.subplots(
    nrows=3,
    ncols=1,
    figsize=(7, 8),
    sharex=True
)


# Voltage

axes[0].plot(
    data["Time_s"],
    data["Voltage_V"],
    linewidth=2
)

axes[0].set_ylabel(
    "Voltage [V]"
)

axes[0].grid(
    True
)


# Current

axes[1].plot(
    data["Time_s"],
    data["Current_A"],
    linewidth=2
)

axes[1].set_ylabel(
    "Current [A]"
)

axes[1].grid(
    True
)


# Power

axes[2].plot(
    data["Time_s"],
    data["Power_W"],
    linewidth=2
)

axes[2].set_xlabel(
    "Time [s]"
)

axes[2].set_ylabel(
    "Power [W]"
)

axes[2].grid(
    True
)


fig.suptitle(
    "Converter Measurements from CSV"
)


plt.tight_layout()

plt.show()


# ============================================================
# 25. SELECT SEVERAL COLUMNS
# ============================================================

"""
Suppose a large CSV contains many variables.

We can define the required columns explicitly.
"""


selected_columns = [
    "Voltage_V",
    "Current_A",
    "Power_W"
]


print(
    "\n--- Selected Columns ---"
)

print(
    selected_columns
)


# ============================================================
# 26. SELECT DATAFRAME SUBSET
# ============================================================

"""
Several columns can be selected simultaneously.
"""


selected_data = data[
    selected_columns
]


print(
    "\n--- Selected Data ---"
)

print(
    selected_data.head()
)


# ============================================================
# 27. AUTOMATIC SUBPLOTS FROM SELECTED COLUMNS
# ============================================================

"""
This is a useful pattern for engineering datasets.

Instead of manually writing one plotting command for every
column, Python can loop through selected variables.
"""


axis_labels = {

    "Voltage_V": "Voltage [V]",

    "Current_A": "Current [A]",

    "Power_W": "Power [W]"

}


number_of_plots = len(
    selected_columns
)


fig, axes = plt.subplots(
    number_of_plots,
    1,
    figsize=(
        7,
        2.5 * number_of_plots
    ),
    sharex=True
)


# Ensure axes always behaves as a list-like structure

if number_of_plots == 1:

    axes = [
        axes
    ]


for ax, column in zip(
    axes,
    selected_columns
):

    ax.plot(
        data["Time_s"],
        data[column],
        linewidth=2
    )


    ax.set_ylabel(
        axis_labels.get(
            column,
            column
        )
    )


    ax.grid(
        True
    )


axes[-1].set_xlabel(
    "Time [s]"
)


fig.suptitle(
    "Selected CSV Variables"
)


plt.tight_layout()

plt.show()


# ============================================================
# 28. SELECT ROWS
# ============================================================

"""
Pandas can also select only part of the dataset.

Example:

First 10 rows.
"""


first_10_rows = data.iloc[
    0:10
]


print(
    "\n--- First 10 Rows ---"
)

print(
    first_10_rows
)


# ============================================================
# 29. PLOT SELECTED ROWS
# ============================================================

fig, ax = plt.subplots(
    figsize=(7, 4.5)
)


ax.plot(
    first_10_rows["Time_s"],
    first_10_rows["Voltage_V"],
    marker="o"
)


ax.set_xlabel(
    "Time [s]"
)

ax.set_ylabel(
    "Voltage [V]"
)

ax.set_title(
    "First 10 CSV Samples"
)


ax.grid(
    True
)


plt.tight_layout()

plt.show()


# ============================================================
# 30. FILTER DATA USING A CONDITION
# ============================================================

"""
Suppose we only want:

Time <= 0.010 s
"""


filtered_data = data[
    data["Time_s"] <= 0.010
]


print(
    "\n--- Filtered Dataset ---"
)

print(
    filtered_data
)


# ============================================================
# 31. PLOT FILTERED DATA
# ============================================================

fig, ax = plt.subplots(
    figsize=(7, 4.5)
)


ax.plot(
    filtered_data["Time_s"],
    filtered_data["Voltage_V"],
    marker="o"
)


ax.set_xlabel(
    "Time [s]"
)

ax.set_ylabel(
    "Voltage [V]"
)

ax.set_title(
    "Filtered Voltage Data"
)


ax.grid(
    True
)


plt.tight_layout()

plt.show()


# ============================================================
# 32. FILTER BETWEEN TWO VALUES
# ============================================================

"""
Example:

Select:

0.005 <= Time <= 0.015 seconds
"""


start_time = 0.005

end_time = 0.015


time_window = data[
    (
        data["Time_s"]
        >= start_time
    )
    &
    (
        data["Time_s"]
        <= end_time
    )
]


print(
    "\n--- Selected Time Window ---"
)

print(
    time_window
)


# ============================================================
# 33. PLOT SELECTED TIME WINDOW
# ============================================================

fig, ax = plt.subplots(
    figsize=(7, 4.5)
)


ax.plot(
    time_window["Time_s"],
    time_window["Voltage_V"],
    marker="o"
)


ax.set_xlabel(
    "Time [s]"
)

ax.set_ylabel(
    "Voltage [V]"
)

ax.set_title(
    "Voltage within Selected Time Window"
)


ax.grid(
    True
)


plt.tight_layout()

plt.show()


# ============================================================
# 34. CHECK FOR MISSING VALUES
# ============================================================

"""
Real engineering datasets may contain missing values.

Pandas represents many missing numerical values as:

NaN


isna() identifies missing values.
"""


print(
    "\n--- Missing Values per Column ---"
)

print(
    data.isna().sum()
)


# ============================================================
# 35. REMOVE MISSING VALUES
# ============================================================

"""
dropna() removes rows containing missing values.

Be careful:

Do not remove experimental data automatically without
understanding why values are missing.
"""


clean_data = data.dropna()


print(
    "\nRows before cleaning:",
    len(data)
)

print(
    "Rows after cleaning:",
    len(clean_data)
)


# ============================================================
# 36. NUMERICAL CONVERSION
# ============================================================

"""
Sometimes a numerical CSV column contains text such as:

ERROR

N/A

invalid


Pandas can attempt numerical conversion using:

pd.to_numeric()


errors="coerce"

converts invalid entries into NaN.
"""


numerical_columns = [
    "Time_s",
    "Voltage_V",
    "Current_A",
    "Power_W"
]


clean_numeric_data = data.copy()


for column in numerical_columns:

    clean_numeric_data[
        column
    ] = pd.to_numeric(

        clean_numeric_data[
            column
        ],

        errors="coerce"

    )


# Remove rows containing invalid numerical values

clean_numeric_data = (
    clean_numeric_data.dropna(
        subset=numerical_columns
    )
)


# ============================================================
# 37. VERIFY DATA AFTER CLEANING
# ============================================================

print(
    "\n--- Clean Numerical Dataset ---"
)

print(
    clean_numeric_data.head()
)


print(
    "\nClean Data Types:"
)

print(
    clean_numeric_data.dtypes
)


# ============================================================
# 38. CALCULATE A NEW COLUMN
# ============================================================

"""
Pandas allows new variables to be calculated directly.

Example:

Calculated Power:

P = V * I
"""


data[
    "Calculated_Power_W"
] = (

    data["Voltage_V"]

    * data["Current_A"]

)


print(
    "\n--- Dataset with Calculated Power ---"
)

print(
    data.head()
)


# ============================================================
# 39. COMPARE ORIGINAL AND CALCULATED POWER
# ============================================================

fig, ax = plt.subplots(
    figsize=(7, 4.5)
)


ax.plot(
    data["Time_s"],
    data["Power_W"],
    linewidth=2,
    label="Power from CSV"
)


ax.plot(
    data["Time_s"],
    data["Calculated_Power_W"],
    linestyle="--",
    linewidth=2,
    label="Calculated V × I"
)


ax.set_xlabel(
    "Time [s]"
)

ax.set_ylabel(
    "Power [W]"
)

ax.set_title(
    "CSV Power Validation"
)


ax.grid(
    True
)

ax.legend()


plt.tight_layout()

plt.show()


# ============================================================
# 40. SAVE PROCESSED CSV
# ============================================================

"""
Processed data can also be saved back to CSV.

index=False prevents Pandas from adding its own numerical
row index as an extra CSV column.
"""


output_data_folder = (
    script_folder
    / "output_data"
)


output_data_folder.mkdir(
    exist_ok=True
)


processed_csv = (
    output_data_folder
    / "processed_voltage_current.csv"
)


data.to_csv(
    processed_csv,
    index=False
)


print(
    "\nProcessed CSV saved to:"
)

print(
    processed_csv
)


# ============================================================
# 41. REUSABLE CSV PLOTTING FUNCTION
# ============================================================

"""
A reusable function can load and plot any selected
X and Y columns.

This demonstrates how repetitive plotting code can be
converted into a general tool.
"""


def plot_csv_column(
    filename,
    x_column,
    y_column,
    x_label,
    y_label,
    title
):
    """
    Load a CSV file and plot one Y column against one
    X column.

    Parameters
    ----------
    filename : str or Path
        Path to CSV file.

    x_column : str
        Column used for X-axis.

    y_column : str
        Column used for Y-axis.

    x_label : str
        X-axis label.

    y_label : str
        Y-axis label.

    title : str
        Figure title.
    """

    filename = Path(
        filename
    )


    if not filename.exists():

        raise FileNotFoundError(
            f"CSV file not found: "
            f"{filename}"
        )


    dataframe = pd.read_csv(
        filename
    )


    if x_column not in dataframe.columns:

        raise KeyError(
            f"X column '{x_column}' not found."
            f"\nAvailable columns:"
            f"\n{dataframe.columns.tolist()}"
        )


    if y_column not in dataframe.columns:

        raise KeyError(
            f"Y column '{y_column}' not found."
            f"\nAvailable columns:"
            f"\n{dataframe.columns.tolist()}"
        )


    fig, ax = plt.subplots(
        figsize=(7, 4.5)
    )


    ax.plot(
        dataframe[x_column],
        dataframe[y_column],
        linewidth=2
    )


    ax.set_xlabel(
        x_label
    )

    ax.set_ylabel(
        y_label
    )

    ax.set_title(
        title
    )


    ax.grid(
        True
    )


    plt.tight_layout()

    plt.show()


# ============================================================
# 42. USE THE REUSABLE FUNCTION
# ============================================================

plot_csv_column(

    filename=csv_file,

    x_column="Time_s",

    y_column="Voltage_V",

    x_label="Time [s]",

    y_label="Voltage [V]",

    title="Voltage Loaded from CSV"

)


# ============================================================
# 43. REUSABLE MULTI-COLUMN SUBPLOT FUNCTION
# ============================================================

"""
Now create a more useful function for engineering data.

The user specifies:

- CSV file
- X column
- Several Y columns
- Axis labels

Python generates the subplots automatically.
"""


def plot_csv_subplots(
    filename,
    x_column,
    y_columns,
    y_labels,
    x_label,
    title
):
    """
    Plot several CSV columns as vertically stacked subplots.
    """

    filename = Path(
        filename
    )


    if not filename.exists():

        raise FileNotFoundError(
            f"CSV file not found: "
            f"{filename}"
        )


    dataframe = pd.read_csv(
        filename
    )


    required_columns = [
        x_column
    ] + y_columns


    missing_columns = [

        column

        for column in required_columns

        if column not in dataframe.columns

    ]


    if missing_columns:

        raise KeyError(
            f"Missing columns: "
            f"{missing_columns}"
            f"\nAvailable columns:"
            f"\n{dataframe.columns.tolist()}"
        )


    if len(
        y_columns
    ) != len(
        y_labels
    ):

        raise ValueError(
            "Number of Y columns must match "
            "number of Y-axis labels."
        )


    number_of_plots = len(
        y_columns
    )


    fig, axes = plt.subplots(
        number_of_plots,
        1,
        figsize=(
            7,
            2.5 * number_of_plots
        ),
        sharex=True
    )


    if number_of_plots == 1:

        axes = [
            axes
        ]


    for ax, column, label in zip(

        axes,

        y_columns,

        y_labels

    ):

        ax.plot(
            dataframe[
                x_column
            ],
            dataframe[
                column
            ],
            linewidth=2
        )


        ax.set_ylabel(
            label
        )

        ax.grid(
            True
        )


    axes[-1].set_xlabel(
        x_label
    )


    fig.suptitle(
        title
    )


    plt.tight_layout()

    plt.show()


# ============================================================
# 44. USE MULTI-COLUMN FUNCTION
# ============================================================

plot_csv_subplots(

    filename=csv_file,

    x_column="Time_s",

    y_columns=[
        "Voltage_V",
        "Current_A",
        "Power_W"
    ],

    y_labels=[
        "Voltage [V]",
        "Current [A]",
        "Power [W]"
    ],

    x_label="Time [s]",

    title="Converter Measurements from CSV"

)


# ============================================================
# 45. SAVE FINAL FIGURE
# ============================================================

output_figure_folder = (
    script_folder
    / "output_figures"
)


output_figure_folder.mkdir(
    exist_ok=True
)


fig, axes = plt.subplots(
    3,
    1,
    figsize=(7, 8),
    sharex=True
)


axes[0].plot(
    data["Time_s"],
    data["Voltage_V"],
    linewidth=2
)

axes[0].set_ylabel(
    "Voltage [V]"
)

axes[0].grid(
    True
)


axes[1].plot(
    data["Time_s"],
    data["Current_A"],
    linewidth=2
)

axes[1].set_ylabel(
    "Current [A]"
)

axes[1].grid(
    True
)


axes[2].plot(
    data["Time_s"],
    data["Power_W"],
    linewidth=2
)

axes[2].set_xlabel(
    "Time [s]"
)

axes[2].set_ylabel(
    "Power [W]"
)

axes[2].grid(
    True
)


fig.suptitle(
    "Converter Measurements from CSV"
)


plt.tight_layout()


# ============================================================
# 46. SAVE PNG
# ============================================================

png_file = (
    output_figure_folder
    / "csv_measurements.png"
)


fig.savefig(
    png_file,
    dpi=300,
    bbox_inches="tight"
)


# ============================================================
# 47. SAVE PDF
# ============================================================

pdf_file = (
    output_figure_folder
    / "csv_measurements.pdf"
)


fig.savefig(
    pdf_file,
    bbox_inches="tight"
)


# ============================================================
# 48. SAVE SVG
# ============================================================

svg_file = (
    output_figure_folder
    / "csv_measurements.svg"
)


fig.savefig(
    svg_file,
    bbox_inches="tight"
)


print(
    "\n--- Figures Saved ---"
)

print(
    png_file
)

print(
    pdf_file
)

print(
    svg_file
)


plt.show()


# ============================================================
# 49. COMMON MISTAKE - WRONG FILE PATH
# ============================================================

"""
A very common beginner error is:

FileNotFoundError


Example:

pd.read_csv(
    "voltage_current.csv"
)


This searches in the CURRENT WORKING DIRECTORY.

However, the file may actually be inside:

sample_data/


A robust solution is:

script_folder = Path(
    __file__
).resolve().parent


csv_file = (
    script_folder
    / "sample_data"
    / "voltage_current.csv"
)
"""


# ============================================================
# 50. COMMON MISTAKE - WRONG COLUMN NAME
# ============================================================

"""
Suppose the CSV contains:

Voltage_V


but the code uses:

data["Voltage"]


Python raises:

KeyError


Always inspect:

print(
    data.columns
)
"""


# ============================================================
# 51. COMMON MISTAKE - EXTRA SPACES IN COLUMN NAMES
# ============================================================

"""
Some CSV files contain headers such as:

" Voltage "

instead of:

"Voltage"


Column names can be cleaned using:
"""


cleaned_columns_example = data.copy()


cleaned_columns_example.columns = (

    cleaned_columns_example.columns

    .str.strip()

)


# ============================================================
# 52. COMMON MISTAKE - NON-NUMERICAL DATA
# ============================================================

"""
A measurement column may contain:

48.5
49.0
ERROR
50.1


The column may then require cleaning.

Use:

pd.to_numeric(
    column,
    errors="coerce"
)


Invalid entries become NaN and can then be investigated.
"""


# ============================================================
# 53. COMMON MISTAKE - AUTOMATICALLY DELETING DATA
# ============================================================

"""
Avoid blindly applying:

data.dropna()


to research datasets without understanding why values
are missing.

Missing values may indicate:

- Instrument interruption
- Trigger problem
- Measurement failure
- Data corruption
- Real missing observation


Data cleaning must remain scientifically justified.
"""


# ============================================================
# 54. COMMON MISTAKE - MIXING DIFFERENT UNITS
# ============================================================

"""
CSV file contains:

Voltage [V]

Current [A]

Power [W]


Do not automatically plot all columns on one ordinary
Y-axis.

Instead consider:

Subplots

Dual Y-axis

Normalization

Separate figures
"""


# ============================================================
# 55. COMMON MISTAKE - PLOTTING ROW NUMBER INSTEAD OF X
# ============================================================

"""
Pandas allows:

data["Voltage_V"].plot()


but unless an X column is specified, the plot may use
the DataFrame index:

0
1
2
3
...


For engineering time-domain data, the intended X-axis
may actually be:

Time_s


Therefore explicitly using:

ax.plot(
    data["Time_s"],
    data["Voltage_V"]
)

is often clearer.
"""


# ============================================================
# 56. COMMON MISTAKE - NO UNITS
# ============================================================

"""
CSV header:

Voltage_V


is useful for programming.

Figure label:

Voltage [V]


is usually clearer for publication.

Do not assume raw CSV column names must also be used
directly as final figure labels.
"""


# ============================================================
# 57. CSV PLOTTING PIPELINE
# ============================================================

"""
CSV File
   ↓
Locate File
   ↓
Check File Exists
   ↓
pd.read_csv()
   ↓
data.head()
   ↓
data.columns
   ↓
data.dtypes
   ↓
Check Missing Values
   ↓
Select X Column
   ↓
Select Y Column(s)
   ↓
Check Units
   ↓
Clean / Filter if Required
   ↓
Create Plot
   ↓
Add Labels + Units
   ↓
Validate Figure
   ↓
Save Figure
"""


# ============================================================
# 58. PRACTICAL ENGINEERING WORKFLOW
# ============================================================

"""
Oscilloscope / Simulation
          ↓
      Export CSV
          ↓
        Python
          ↓
      pd.read_csv()
          ↓
      Inspect Data
          ↓
      Select Columns
          ↓
      Time Window
          ↓
      Calculation
          ↓
        Plot
          ↓
    Publication Figure
"""


# ============================================================
# KEY TAKEAWAYS
# ============================================================

"""
PLOT FROM CSV


1. READ CSV

import pandas as pd


data = pd.read_csv(
    "data.csv"
)


------------------------------------------------------------


2. ALWAYS INSPECT DATA

print(
    data.head()
)


print(
    data.columns
)


print(
    data.dtypes
)


data.info()


------------------------------------------------------------


3. SELECT COLUMN

time = data[
    "Time_s"
]


voltage = data[
    "Voltage_V"
]


------------------------------------------------------------


4. PLOT COLUMN

ax.plot(
    data["Time_s"],
    data["Voltage_V"]
)


------------------------------------------------------------


5. SELECT MULTIPLE COLUMNS

columns = [
    "Voltage_V",
    "Current_A",
    "Power_W"
]


------------------------------------------------------------


6. DIFFERENT PHYSICAL UNITS

Voltage [V]

Current [A]

Power [W]


Prefer:

Subplots

rather than automatically using one common Y-axis.


------------------------------------------------------------


7. FILTER ROWS

data[
    data["Time_s"] <= 0.010
]


------------------------------------------------------------


8. FILTER RANGE

data[
    (
        data["Time_s"] >= start
    )
    &
    (
        data["Time_s"] <= end
    )
]


------------------------------------------------------------


9. CHECK MISSING DATA

data.isna().sum()


------------------------------------------------------------


10. CONVERT TO NUMERICAL DATA

pd.to_numeric(
    data["Voltage_V"],
    errors="coerce"
)


------------------------------------------------------------


11. CREATE NEW COLUMN

data["Power_W"] = (

    data["Voltage_V"]

    * data["Current_A"]

)


------------------------------------------------------------


12. SAVE PROCESSED DATA

data.to_csv(
    "processed.csv",
    index=False
)


------------------------------------------------------------


13. FILE PATH

Use pathlib for reliable project-relative paths:

script_folder = Path(
    __file__
).resolve().parent


csv_file = (
    script_folder
    / "sample_data"
    / "voltage_current.csv"
)


------------------------------------------------------------


14. COMMON PROBLEMS

FileNotFoundError
    Wrong path

KeyError
    Wrong column name

object data type
    Text inside numerical column

NaN
    Missing/invalid values

Wrong X-axis
    DataFrame index instead of physical variable


------------------------------------------------------------


15. IMPORTANT RESEARCH PRINCIPLE

Do not begin by plotting immediately.

First:

Inspect the dataset.

Understand the columns.

Check the units.

Check the data types.

Check missing values.

Then plot.


------------------------------------------------------------


16. CORE WORKFLOW

CSV
 ↓
Pandas DataFrame
 ↓
Inspect
 ↓
Select
 ↓
Clean
 ↓
Process
 ↓
Plot
 ↓
Save


------------------------------------------------------------


NEXT:

09_plot_from_excel.py


The next file will extend the same workflow to:

Excel Workbook
       ↓
Select Sheet
       ↓
Inspect Sheet Names
       ↓
Read Worksheet
       ↓
Select Columns
       ↓
Plot One Variable
       ↓
Plot Multiple Variables
       ↓
Load Several Sheets
       ↓
Compare Cases
       ↓
Save Figure


We will use:

sample_data/converter_measurements.xlsx
"""
